'use client';
import { useEffect, useState } from 'react';
import { Shield, ArrowUpRight, Copy, Check, ChevronRight, CircleDot, Wallet, KeyRound, Activity, LockKeyhole, Plus, X } from 'lucide-react';

type Mode = 'injected';
const demo: Array<{id:string;title:string;target:string;status:string;tone:string;risk:string;when:string;hash:string}> = [];
const emptyProposal = {id:'—', title:'No proposals on StudioNet yet', target:'Create the first proposal to populate this queue.', status:'EMPTY', tone:'cyan', risk:'—', when:'—', hash:'—'};

export default function Home(){
 const [mode,setMode]=useState<Mode>('injected'); const [address,setAddress]=useState(''); const [copied,setCopied]=useState(false); const [open,setOpen]=useState(false); const [active,setActive]=useState(emptyProposal);
 useEffect(()=>{ const eth=(window as any).ethereum; if(!eth) return; eth.request({method:'eth_accounts'}).then((a:string[])=>{if(a?.[0]) setAddress(a[0]);}); },[]);
 const connectInjected=async()=>{ const eth=(window as any).ethereum; if(!eth){return;} const a=await eth.request({method:'eth_requestAccounts'}); setAddress(a[0]); setMode('injected'); };
 const copy=()=>{navigator.clipboard.writeText(address);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <main><header><div className="brand"><div className="mark"><Shield size={19}/></div><span>ATROOT</span><small>COMMAND FIREWALL</small></div><div className="top-actions"><div className="network"><CircleDot size={11}/> STUDIONET <b>61999</b></div><button className="wallet-btn" onClick={()=>setOpen(true)}><Wallet size={16}/>{address?`${address.slice(0,6)}…${address.slice(-4)}`:'CONNECT WALLET'}</button></div></header>
 <section className="hero"><div className="eyebrow"><span className="pulse"/> LIVE CONTROL PLANE / 03 ACTIVE PROPOSALS</div><h1>Let agents act.<br/><em>Make authority legible.</em></h1><p>ATROOT turns consequential agent actions into a verifiable command chain — charter, semantic review, exact bytes, and post-state proof.</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}>Connect to operate <ArrowUpRight size={17}/></button><button className="text-btn" onClick={()=>document.getElementById('operations')?.scrollIntoView({behavior:'smooth'})}>Browse audit trail <ChevronRight size={16}/></button></div></section>
 <section id="operations" className="workspace"><div className="workspace-head"><div><div className="section-kicker">OPERATIONS / PROPOSALS</div><h2>Command queue</h2></div><button className="new-btn" onClick={()=>setOpen(true)}><Plus size={16}/> New proposal</button></div><div className="layout"><div className="proposal-list">{demo.map(p=><button className={`proposal ${active.id===p.id?'selected':''}`} key={p.id} onClick={()=>setActive(p)}><div className="proposal-top"><span className={`status ${p.tone}`}>{p.status}</span><span className="risk">{p.risk} RISK</span></div><strong>{p.title}</strong><span className="target">{p.target}</span><div className="proposal-foot"><span>{p.id}</span><span>{p.when}</span></div></button>)}</div><div className="dossier"><div className="dossier-head"><div><span className={`status ${active.tone}`}>{active.status}</span><h3>{active.title}</h3><p>Proposal {active.id} · semantic review in progress</p></div><button className="icon-btn" aria-label="copy proposal id" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="command-grid"><div><label>PROTECTED TARGET</label><code>{active.target}</code></div><div><label>BOUND ACTION HASH</label><code>{active.hash}</code></div><div><label>CHARTER VERSION</label><span>authority-v7 <i>valid</i></span></div><div><label>SUBMITTED BY</label><span className="address">{address||'browser wallet not connected'}</span></div></div><div className="consensus"><div className="consensus-title"><Activity size={17}/> CONSENSUS ROOM <span>validator interpretation</span></div><div className="stages"><div className="stage done"><b>01</b><span>PROPOSE</span></div><div className="stage current"><b>02</b><span>REVIEW</span></div><div className="stage"><b>03</b><span>CHALLENGE</span></div><div className="stage"><b>04</b><span>SETTLE</span></div></div><p className="consensus-note">Validators are comparing the action against the signed charter and fetched evidence. No authority is granted until the decision is finalized.</p></div><div className="dossier-actions"><button className="secondary">View evidence <ArrowUpRight size={15}/></button><button className="danger">Reject proposal</button></div></div></div></section>
 <footer><span>ATROOT / SEMANTIC AUTHORITY FOR AGENT SYSTEMS</span><span>GENLAYER <b>STUDIONET</b> · READ-ONLY BROWSING ENABLED</span></footer>
 {open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="section-kicker">IDENTITY LAYER</div><h2>Connect an injected wallet.</h2><p className="modal-copy">Reads are public. Writes require an explicit EIP-1193 wallet connection on StudioNet.</p><button className="wallet-option active" onClick={connectInjected}><div className="option-icon"><Wallet size={18}/></div><div><strong>Injected wallet</strong><span>MetaMask, Rabby, or any EIP-1193 wallet</span></div><ChevronRight size={17}/></button>{address&&<div className="identity"><label>ACTIVE IDENTITY · INJECTED</label><code>{address}</code><button onClick={copy}>{copied?'COPIED':'COPY'}</button></div>}</div></div>}
 </main>
}
