import { createAccount, createClient } from 'genlayer-js';
import { TransactionStatus } from 'genlayer-js/types';
import { chain, chainName, contractAddress, rpcEndpoint } from './config';
import type { Proposal } from './types';

const address = () => { if (!contractAddress) throw new Error('ATROOT contract address is not configured.'); return contractAddress as `0x${string}`; };
export async function listProposals(): Promise<Proposal[]> { const client=createClient({chain,endpoint:rpcEndpoint,account:createAccount()}); const result=await client.readContract({address:address(),functionName:'list_proposals',args:[BigInt(0),BigInt(100)]}); return Array.isArray(result)?result as Proposal[]:[]; }
export async function getProposal(id:number): Promise<Proposal> { const client=createClient({chain,endpoint:rpcEndpoint,account:createAccount()}); return await client.readContract({address:address(),functionName:'get_proposal',args:[BigInt(id)]}) as Proposal; }
export async function writeProposal(account:string|`0x${string}`, title:string,target:string,actionHash:string,intent:string,charter:string, browserKey?:`0x${string}`){ const client=browserKey?createClient({chain,endpoint:rpcEndpoint,account:createAccount(browserKey)}):createClient({chain,endpoint:rpcEndpoint,account:account as `0x${string}`}); if(!browserKey) await client.connect(chainName); const hash=await client.writeContract({address:address(),functionName:'create_proposal',args:[title,target,actionHash,intent,charter],value:BigInt(0)}); return client.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:5000,retries:90}); }
export async function reviewProposal(account:string|`0x${string}`, id:number,evidenceUrl:string,browserKey?:`0x${string}`){ const client=browserKey?createClient({chain,endpoint:rpcEndpoint,account:createAccount(browserKey)}):createClient({chain,endpoint:rpcEndpoint,account:account as `0x${string}`}); if(!browserKey) await client.connect(chainName); const hash=await client.writeContract({address:address(),functionName:'review_proposal',args:[BigInt(id),evidenceUrl],value:BigInt(0)}); return client.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:5000,retries:90}); }
