'use client';
import { useEffect,useState } from 'react';
import { createAccount,generatePrivateKey } from 'genlayer-js';
import Shell from '../../components/shell';
export default function Settings(){
 const [mode,setMode]=useState('injected'); const [address,setAddress]=useState(''); const [key,setKey]=useState(''); const [copied,setCopied]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('atroot.browserPrivateKey') as `0x${string}`|null;if(saved){setKey(saved);setAddress(createAccount(saved).address);setMode('browser');return}const eth=(window as any).ethereum;if(eth)eth.request({method:'eth_accounts'}).then((a:string[])=>a?.[0]&&setAddress(a[0]));},[]);
 const copy=async(value=address)=>{if(!value)return;await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1000)};
 const create=()=>{let k=localStorage.getItem('atroot.browserPrivateKey') as `0x${string}`|null;if(!k){k=generatePrivateKey();localStorage.setItem('atroot.browserPrivateKey',k)}setKey(k);setAddress(createAccount(k).address);setMode('browser')};
 const exportKey=()=>{const value=key||localStorage.getItem('atroot.browserPrivateKey')||'';const blob=new Blob([value],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='atroot-private-key.txt';a.click();URL.revokeObjectURL(a.href)};
 return <Shell><main className="page settings"><div className="section-kicker">CONTROL PLANE / IDENTITY</div><h1>Wallet & network</h1><p className="lede">Injected wallets never expose their secret. Browser wallets are local-only and experimental.</p><div className="settings-grid"><section className="setting-card"><label>ACTIVE WALLET · {mode.toUpperCase()}</label>{address?<><code>{address}</code><div className="identity-actions"><button className="secondary" onClick={()=>copy()}>{copied?'COPIED':'COPY ADDRESS'}</button>{mode==='browser'&&<button className="secondary" onClick={exportKey}>EXPORT PRIVATE KEY</button>}</div></>:<button className="primary" onClick={()=>{const eth=(window as any).ethereum;if(eth)eth.request({method:'eth_requestAccounts'}).then((a:string[])=>{setAddress(a[0]);setMode('injected')})}}>Connect injected wallet</button>}</section><section className="setting-card"><label>BROWSER WALLET</label><p>Generate or restore the local development identity used for testing.</p><button className="secondary" onClick={create}>{key?'SHOW BROWSER WALLET':'CREATE BROWSER WALLET'}</button>{key&&<><code>{address}</code><div className="identity-actions"><button className="secondary" onClick={()=>copy(address)}>COPY ADDRESS</button><button className="secondary" onClick={exportKey}>EXPORT PRIVATE KEY</button></div></>}</section><section className="setting-card"><label>NETWORK</label><code>GenLayer StudioNet · chain 61999</code><code>https://studio.genlayer.com/api</code></section></div></main></Shell>
}
